### ISSUE TITLE
Maps: Use `blurlms 1` before running `calclight` for smoother shadows

### ISSUE THREAD

**Issue by Calinou** [tomatenquark/essential#10]
`blurlms 1` can be used along with halved `lightprecision` to make shadows significantly smoother.

It makes maps larger due to the lower `lightprecision`, but I think the file size difference is acceptable by today's standards. Still, we should only do this for maps where the difference is visible enough. This is often the case on daytime maps, but it's less visible in fully indoor or nighttime maps.

*Click to view screenshots at full size.*

## Current: `blank` with `lightprecision 16; blurlms 0` (file size: 550 KB)

![blank](https://user-images.githubusercontent.com/180032/82131543-8e096f80-97d6-11ea-8a66-35a5a99096fb.png)

## Proposed: `blank` with `lightprecision 8; blurlms 1` (file size: 1.1 MB)

![2020-05-17_00 34 11_blank_instagib](https://user-images.githubusercontent.com/180032/82131594-0d973e80-97d7-11ea-9d41-2e9e1f08cd8e.png)

**Comment by Fohlen** [comment]
Hey. After evaluating this on my retina display I decided that it likewise is a good step to take.
@Calinou or @SalatielSauer could we do this? And can we also add it to the mapping guideline?

All the best

**Comment by SalatielSauer** [comment]
awesome, added here [62dfe33](https://github.com/tomatenquark/essential/commit/62dfe330997188279eaebc29a5284702c037fe28)

**Comment by Fohlen** [comment]
@SalatielSauer if I understand correctly we want to do this for all maps, not just blank

**Comment by Fohlen** [comment]
Also we need to do calclight again

**Comment by SalatielSauer** [comment]
working on it right now

**Comment by SalatielSauer** [comment]
done [here](https://github.com/tomatenquark/essential/compare/36fc566973c3...8e98050a6928)
I think the author/mapper has a more accurate look at what's best for the performance of his map, for this reason I did not change the value of lightprecision in most of them.

**Comment by Fohlen** [comment]
Seems legitimate. Closing.
