### ISSUE TITLE
Investigate using Inter UI as default font

### ISSUE THREAD

**Issue by Calinou** [tomatenquark/essential#11]
Last year, I released [High-resolution Inter font](http://quadropolis.us/node/4345) on Quadropolis. It's a port of [Inter UI](rsms.me/inter/) to Sauerbraten. Since it's an open source font licensed under the SIL OFL, we can use it for Tomatenquark.

The benefits compared to the current font are:

- Higher resolution (HUD numbers look good in 1440p and 4K)
- Thinner outlines (looks better at higher resolutions)

**Comment by Fohlen** [comment]
Can you try this and post some screenshots here or on Discord?

**Comment by Calinou** [comment]
I grabbed the ZIP from Quadropolis and installed it in Tomatenquark, here are the results:

## Menu

### Default font

![menu_default](https://user-images.githubusercontent.com/180032/82155832-e5135100-9877-11ea-887e-747847bc6685.png)

### Inter UI

Don't mind the misaligned GUI element, it should be fixable easily afterwards.

![menu_inter_ui](https://user-images.githubusercontent.com/180032/82155833-e6447e00-9877-11ea-9813-642b541ac9fc.png)

## Game

Notice how the HUD numbers are sharper with Inter UI.

### Default

![game_default](https://user-images.githubusercontent.com/180032/82155829-e17fca00-9877-11ea-9f21-342bef9c6f9a.png)

### Inter UI

![game_inter_ui](https://user-images.githubusercontent.com/180032/82155831-e47aba80-9877-11ea-8fa7-40263e80544b.png)

**Comment by SalatielSauer** [comment]
I think we can make it optional, would it work if executed after data/font.cfg?

**Comment by Fohlen** [comment]
Can we tackle this before the upcoming release?
