### ISSUE TITLE
Your license policy directly conflicts with your used licenses

### ISSUE THREAD

**Issue by Croydon** [tomatenquark/essential#6]
Your [license policy](https://tomatenquark.org/media/LICENSING.html) - which you might have copied over from [Inexor](https://inexor.org/wiki/License-Policy.html) without reflecting about it - directly conflicts with the [list of used licenses](https://tomatenquark.org/media/USED_LICENSES.html).

If you want to count as a free and libre open source project, you need to get rid of - **at the very least** - all content under licenses that forbids commercial use.

For additional clarity, you might also want to get rid of custom licenses as the Soundsnap license.

If this is your plan, but work-in-progress, please make this clearer. However, recent activities like [re-enabling](https://github.com/tomatenquark/code/commit/aad313a9ab631d73a96daade01bf6c9f4e163a4b) [Mr. Fixit](https://github.com/tomatenquark/code/commit/0f43bac19706dc9d8d7b91a04e11f8579165eb29), which is [under CC-BY-NC](https://github.com/tomatenquark/essential/blob/b2c58674be4a0e3ccfd484ea6c18c39ffe56f549/packages/models/mrfixit/license.txt#L1) license, seem to contradict this.

If it is not your plan to be a free and libre open source project, please update your license policy and your outlined goals.

**Comment by Fohlen** [comment]
Dear @Croydon, thanks for your interest.

Our goal is indeed to replace content with more suitably-licensed content in the future.
For now, the repository is in a state where the game can be reasonably released onto Steam and other platforms.

All the content that is not in accordance with the license policy is old content, that will eventually be replaced. All new content that has been added by any of the TQ members has been licensed under CC BY 4.0

We will replace/remove all of the old content eventually. Creating this quality content however requires  a decent amount of time.

**Comment by Fohlen** [comment]
@Croydon a little heads up on the issue: we marked all the conflicting licenses in bold on the list of used licenses, and are actively working on getting things on track 100%. It is also noteworthy that a decent amount of authors of existing works have waived their work to be relicensed by the TQ project under CC BY-SA 4.0 or CC 0 (e.g the works by Nieb, aard and makKe).

**Comment by Croydon** [comment]
Nieb has started a long time ago to put all content under CC-0. It is nice to hear that aard and makKe reconsidered. 

I wrote this License Policy for Inexor, which TQ copied 1:1, so please give at least credits on this wiki page

**Comment by Croydon** [comment]
Closing as the project does neither care to give credits nor do they care that their copied license policy is conflicting with their content.

**Comment by qreeves** [comment]
It's not really a matter of not caring, but the project isn't really under active development anymore. You never made it clear you wanted Inexor to be given credit, but I should note also that there's no license attached to the license policy for Inexor (so it is probably inappropriate to use it at all).
